### PR TITLE
Consistent submodule initialization with libmailcore.com

### PR DESCRIPTION
**Pull request by mkdynamic**

### CODE REVIEW

**Comment by mronge** [comment]
Thanks!

**Comment by jwilling** [comment]
I'm curious. Wouldn't this accomplish exactly the same thing in just one line?

```
git clone https://github.com/mronge/MailCore.git --recursive
```

**Comment by mronge** [comment]
Yea, that's even better.

## 

Matt Ronge

iOS Developer & Consultant
Central Atomics Inc.
http://www.centralatomics.com

**Comment by jwilling** [comment]
Does that work correctly, though?

**Pull request merged**
